export const genreMap: Record<string, string> = {
  action: 'Action/Adventure',
  animeSeriesInternationalTvShows: 'Anime/Intl. TV',
  britishTvShowsDocuseriesInternationalTvShows: 'British/Intl. TV Shows',
  children: 'Children & Family',
  comedies: 'Comedies',
  comediesDramasInternationalMovies: 'Comedies/Dramas Intl.',
  comediesInternationalMovies: 'Comedies Intl.',
  comediesRomanticMovies: 'Romantic Comedies',
  crimeTvShowsDocuseries: 'Crime & Docuseries',
  documentaries: 'Documentaries',
  documentariesInternationalMovies: 'Docs Intl.',
  docuseries: 'Docuseries',
  dramas: 'Dramas',
  dramasInternationalMovies: 'Dramas Intl.',
  dramasRomanticMovies: 'Romantic Dramas',
  familyMovies: 'Family Movies',
  fantasy: 'Fantasy',
  horrorMovies: 'Horror',
  internationalMoviesThrillers: 'Intl. Thrillers',
  internationalTvShowsRomanticTvShowsTvDramas: 'Intl. Romance/Drama TV',
  kidsTv: 'Kids TV',
  languageTvShows: 'Language TV',
  musicals: 'Musicals',
  natureTv: 'Nature TV',
  realityTv: 'Reality TV',
  spirituality: 'Spirituality',
  tvAction: 'TV Action',
  tvComedies: 'TV Comedies',
  tvDramas: 'TV Dramas',
  talkShowsTvComedies: 'Talk Shows/Comedies',
  thrillers: 'Thrillers',
};
